const gamesData = {
  "games": [
    {
      "id": 1,
      "gameId": "1v1lol",
      "name": "1v1 LOL",
      "description": "Fast-paced 1v1 battle royale game with building mechanics. Test your skills against other players in intense combat.",
      "icon": "assets/1v1lol.png",
      "link": null,
      "raw-game-link": "game-assets/1v1-lol/index.html",
      "category": "Battle Royale",
      "tags": ["battle royale", "building", "combat", "competitive"]
    },
    {
      "id": 2,
      "gameId": "clusterrush",
      "name": "Cluster Rush",
      "description": "Navigate through challenging obstacle courses with precise timing and quick reflexes in this addictive platformer.",
      "icon": "assets/cluster-rush.png",
      "link": null,
      "raw-game-link": "/game-assets/cluster-rush/index.html",
      "category": "Platformer",
      "tags": ["platformer", "obstacles", "timing", "challenging"]
    },
    {
      "id": 3,
      "gameId": "cookieclicker",
      "name": "Cookie Clicker",
      "description": "The ultimate idle clicking game. Build your cookie empire and unlock upgrades to maximize your cookie production.",
      "icon": "assets/cookie-clicker.png",
      "link": null,
      "raw-game-link": "/game-assets/cookieclicker/index.html",
      "category": "Idle",
      "tags": ["idle", "clicker", "incremental", "casual"]
    },
    {
      "id": 4,
      "gameId": "polytrack",
      "name": "Polytrack",
      "description": "Race through colorful geometric tracks in this high-speed racing game with stunning visual effects.",
      "icon": "assets/polytrack.jpg",
      "link": null,
      "raw-game-link": "game-assets/polytrack/index.html",
      "category": "Racing",
      "tags": ["racing", "speed", "geometric", "colorful"]
    },
    {
      "id": 5,
      "gameId": "ragdollarchers",
      "name": "Ragdoll Archers",
      "description": "Physics-based archery combat with ragdoll mechanics. Aim carefully and watch your enemies fall in hilarious ways.",
      "icon": "assets/ragdoll-archers.jpg",
      "link": null,
      "raw-game-link": "/game-assets/RagdollArchers/index.html",
      "category": "Action",
      "tags": ["archery", "physics", "ragdoll", "combat", "funny"]
    },
    {
      "id": 6,
      "gameId": "snowrider3d",
      "name": "Snow Rider 3D",
      "description": "Race down snowy mountain slopes on your sled in this thrilling 3D winter sports game. Avoid obstacles, collect gifts, and master the slopes!",
      "icon": "assets/snow-rider-3d.jpg",
      "link": null,
      "raw-game-link": "/game-assets/snow-rider-3d/game.html",
      "category": "Racing",
      "tags": ["3d", "winter", "sledding", "obstacles", "snow", "racing", "sports"]
    },
    {
      "id": 7,
      "gameId": "leveldevil",
      "name": "Level Devil",
      "description": "Navigate through devilishly difficult platformer levels filled with traps, spikes, and unexpected surprises. Can you outsmart the devil's tricks?",
      "icon": "assets/level-devil.jpg",
      "link": null,
      "raw-game-link": "/game-assets/leveldevil/index.html",
      "category": "Platformer",
      "tags": ["platformer", "difficult", "traps", "puzzle", "challenging", "devil", "precision"]
    },
    {
      "id": 8,
      "gameId": "bikeobby",
      "name": "Bike Obby",
      "description": "Navigate challenging obstacle courses on your bike in this thrilling obby-style game. Master jumps, avoid traps, and reach the finish line!",
      "icon": "assets/bike-obby.jpg",
      "link": null,
      "raw-game-link": "/game-assets/bikeobby/index.html",
      "category": "Sports",
      "tags": ["bike", "obby", "obstacles", "racing", "stunts", "challenging", "parkour"]
    },
    {
      "id": 9,
      "gameId": "drivemad",
      "name": "Drive Mad",
      "description": "Navigate crazy obstacle courses with your vehicle in this physics-based driving game. Balance speed and control to reach the finish line without crashing!",
      "icon": "assets/drive-mad.png",
      "link": null,
      "raw-game-link": "/game-assets/drive-mad/index.html",
      "category": "Racing",
      "tags": ["driving", "physics", "obstacles", "balance", "crazy", "vehicles", "challenging"]
    },
    {
      "id": 10,
      "gameId": "driftboss",
      "name": "Drift Boss",
      "description": "Master the art of drifting in this endless driving game. Keep your car on the winding track as long as possible while performing perfect drifts!",
      "icon": "assets/drift-boss.png",
      "link": null,
      "raw-game-link": "/game-assets/driftboss/index.html",
      "category": "Racing",
      "tags": ["drifting", "endless", "driving", "skill", "precision", "cars", "arcade"]
    },
    {
      "id": 11,
      "gameId": "grannys",
      "name": "Granny's",
      "description": "Escape from Granny's creepy house in this thrilling horror survival game. Solve puzzles, avoid traps, and find your way out before it's too late!",
      "icon": "assets/grannys.jpg",
      "link": null,
      "raw-game-link": "/game-assets/granny/index.html",
      "category": "Horror",
      "tags": ["horror", "escape", "survival", "puzzle", "scary", "stealth", "thriller"]
    },
    {
      "id": 12,
      "gameId": "skyriders",
      "name": "Sky Riders",
      "description": "Soar through the skies in this high-flying adventure game. Navigate aerial challenges, collect power-ups, and master the art of flight!",
      "icon": "assets/sky-riders.jpg",
      "link": null,
      "raw-game-link": "/game-assets/skyriders/index.html",
      "category": "Adventure",
      "tags": ["flying", "aerial", "adventure", "sky", "power-ups", "flight", "soaring"]
    },
    {
      "id": 13,
      "gameId": "retrobowl",
      "name": "Retro Bowl",
      "description": "Experience classic American football in this retro-style sports game. Manage your team, call plays, and lead them to championship glory!",
      "icon": "assets/retro-bowl.png",
      "link": null,
      "raw-game-link": "/game-assets/retrobowl/index.html",
      "category": "Sports",
      "tags": ["football", "retro", "sports", "team", "strategy", "championship", "american"]
    },
    {
      "id": 14,
      "gameId": "tag",
      "name": "Tag",
      "description": "Classic tag game with a twist! Chase and avoid being tagged in this fast-paced multiplayer action game. Quick reflexes and strategy required!",
      "icon": "assets/tag.png",
      "link": null,
      "raw-game-link": "/game-assets/tag/index.html",
      "category": "Action",
      "tags": ["multiplayer", "chase", "fast-paced", "reflexes", "strategy", "classic", "competitive"]
    },
    {
      "id": 16,
      "gameId": "bitlife",
      "name": "BitLife",
      "description": "Live a virtual life from birth to death! Make choices that shape your character's destiny in this addictive life simulation game.",
      "icon": "assets/bitlife.jpg",
      "link": null,
      "raw-game-link": "/game-assets/bitlife/index.html",
      "category": "Simulation",
      "tags": ["life", "simulation", "choices", "virtual", "destiny", "addictive", "character"]
    },
    {
      "id": 17,
      "gameId": "basketballstars",
      "name": "Basketball Stars",
      "description": "Show off your basketball skills in this exciting sports game! Shoot hoops, perform tricks, and compete against players worldwide.",
      "icon": "assets/basketball-stars.png",
      "link": null,
      "raw-game-link": "/game-assets/basketballstars/index.html",
      "category": "Sports",
      "tags": ["basketball", "sports", "shooting", "tricks", "competitive", "skills", "multiplayer"]
    },
    {
      "id": 18,
      "gameId": "ovodimensions",
      "name": "Ovo Dimensions",
      "description": "Navigate through challenging dimensional platformer levels with precise jumps and timing. Master the art of movement in this addictive skill-based game.",
      "icon": "assets/ovo-dimensions.jpg",
      "link": null,
      "raw-game-link": "/game-assets/ovodimensions/index.html",
      "category": "Platformer",
      "tags": ["platformer", "dimensions", "precision", "jumping", "skill", "challenging", "timing"]
    },
    {
      "id": 19,
      "gameId": "gladihoppers",
      "name": "Gladihoppers",
      "description": "Battle as a gladiator in this physics-based fighting game! Use strategy and timing to defeat opponents in the arena with hilarious ragdoll combat.",
      "icon": "assets/gladihoppers.png",
      "link": null,
      "raw-game-link": "/game-assets/gladihoppers/index.html",
      "category": "Action",
      "tags": ["gladiator", "physics", "fighting", "arena", "ragdoll", "combat", "strategy"]
    },
    {
      "id": 20,
      "gameId": "deadlydescent",
      "name": "Deadly Descent",
      "description": "Survive the treacherous mountain descent in this thrilling survival game. Navigate dangerous terrain and avoid deadly obstacles on your way down.",
      "icon": "assets/deadly-descent.jpg",
      "link": null,
      "raw-game-link": "/game-assets/deadlydecent/index.html",
      "category": "Adventure",
      "tags": ["survival", "mountain", "descent", "dangerous", "obstacles", "thrilling", "terrain"]
    },
    {
      "id": 21,
      "gameId": "gunspin",
      "name": "Gunspin",
      "description": "Master the art of gun spinning in this physics-based skill game. Time your shots perfectly and use recoil to propel yourself through challenging levels.",
      "icon": "assets/gunspin.png",
      "link": null,
      "raw-game-link": "/game-assets/gunspin/index.html",
      "category": "Action",
      "tags": ["physics", "shooting", "skill", "recoil", "timing", "challenging", "spinning"]
    },
    {
      "id": 22,
      "gameId": "subwaysurferssp",
      "name": "Subway Surfers SP",
      "description": "Run through the subway tracks in this special edition of the classic endless runner. Collect coins, dodge trains, and surf your way to high scores!",
      "icon": "assets/subway-surfers-sp.png",
      "link": null,
      "raw-game-link": "/game-assets/subway-surfersSP/index.html",
      "category": "Racing",
      "tags": ["endless", "runner", "subway", "coins", "trains", "surfing", "classic"]
    },
    {
      "id": 23,
      "gameId": "idleants",
      "name": "Idle Ants",
      "description": "Build and manage your ant colony in this addictive idle game. Watch your ants work tirelessly to gather resources and expand their underground empire.",
      "icon": "assets/idle-ants.jpg",
      "link": null,
      "raw-game-link": "/game-assets/idle_ants/index.html",
      "category": "Idle",
      "tags": ["idle", "ants", "colony", "management", "resources", "empire", "addictive"]
    },
    {
      "id": 24,
      "gameId": "blockblast",
      "name": "Block Blast",
      "description": "Clear blocks by creating complete lines in this satisfying puzzle game. Strategic placement and quick thinking are key to achieving high scores.",
      "icon": "assets/block-blast.jpg",
      "link": null,
      "raw-game-link": "/game-assets/blockblast/index.html",
      "category": "Puzzle",
      "tags": ["puzzle", "blocks", "lines", "strategy", "satisfying", "thinking", "scores"]
    },
    {
      "id": 25,
      "gameId": "blumgipaintball",
      "name": "Blumgi Paintball",
      "description": "Engage in colorful paintball battles with physics-based gameplay. Aim carefully and use the environment to your advantage in this fun multiplayer shooter.",
      "icon": "assets/blumgi-paintball.png",
      "link": null,
      "raw-game-link": "/game-assets/blumgipaintball/index.html",
      "category": "Action",
      "tags": ["paintball", "physics", "multiplayer", "shooter", "colorful", "battles", "environment"]
    },
    {
      "id": 26,
      "gameId": "eaglercraft",
      "name": "Eaglercraft",
      "description": "Play Minecraft 1.5.2 directly in your browser! Build, explore, and survive in this faithful recreation of the classic sandbox game. No downloads required.",
      "icon": "assets/eaglercraft.png",
      "link": null,
      "raw-game-link": "/game-assets/eaglercraft/index.html",
      "category": "Sandbox",
      "tags": ["minecraft", "sandbox", "building", "survival", "crafting", "browser", "classic"]
    },
    {
      "id": 27,
      "gameId": "slope",
      "name": "Slope",
      "description": "Roll down the endless slope at breakneck speed! Navigate through obstacles and stay on the track in this addictive 3D endless runner.",
      "icon": "assets/slope.jpg",
      "link": null,
      "raw-game-link": "/game-assets/slope/index.html",
      "category": "Racing",
      "tags": ["endless", "3d", "slope", "speed", "obstacles", "rolling", "addictive"]
    },
    {
      "id": 28,
      "gameId": "10minutestilldawn",
      "name": "10 Minutes Till Dawn",
      "description": "Survive waves of enemies for 10 minutes in this intense top-down survival shooter. Upgrade your weapons and abilities to last until dawn!",
      "icon": "assets/10-minutes-till-dawn.png",
      "link": null,
      "raw-game-link": "/game-assets/10minutestilldawn/index.html",
      "category": "Action",
      "tags": ["survival", "shooter", "waves", "upgrade", "intense", "top-down", "dawn"]
    },
    {
      "id": 29,
      "gameId": "2048",
      "name": "2048",
      "description": "Combine numbered tiles to reach 2048! Slide tiles in four directions to merge identical numbers in this addictive puzzle game.",
      "icon": "assets/2048.png",
      "link": null,
      "raw-game-link": "/game-assets/2048/index.html",
      "category": "Puzzle",
      "tags": ["numbers", "tiles", "merge", "puzzle", "addictive", "strategy", "2048"]
    },
    {
      "id": 31,
      "gameId": "60sbr",
      "name": "60 Second Burger Run",
      "description": "Serve customers quickly in this fast-paced restaurant management game! Take orders, cook burgers, and keep customers happy in 60 seconds.",
      "icon": "assets/60-second-burger-run.png",
      "link": null,
      "raw-game-link": "/game-assets/60sbr/index.html",
      "category": "Simulation",
      "tags": ["restaurant", "management", "fast-paced", "cooking", "customers", "burgers", "time"]
    },
    {
      "id": 32,
      "gameId": "danceoffireandice",
      "name": "A Dance of Fire and Ice",
      "description": "Follow the rhythm in this challenging music game! Navigate two orbiting planets through intricate paths while staying in perfect sync with the beat.",
      "icon": "assets/dance-of-fire-and-ice.png",
      "link": null,
      "raw-game-link": "/game-assets/a-dance-of-fire-ice/index.html",
      "category": "Music",
      "tags": ["rhythm", "music", "challenging", "planets", "sync", "beat", "dance"]
    },
    {
      "id": 33,
      "gameId": "adarkroom",
      "name": "A Dark Room",
      "description": "Start with nothing but a flickering fire and build a thriving civilization in this minimalist text-based adventure. Explore, gather resources, and uncover mysteries.",
      "icon": "assets/a-dark-room.png",
      "link": null,
      "raw-game-link": "/game-assets/adarkroom/index.html",
      "category": "Adventure",
      "tags": ["text-based", "minimalist", "civilization", "resources", "exploration", "mystery", "incremental"]
    },
    {
      "id": 34,
      "gameId": "adventurecapitalist",
      "name": "Adventure Capitalist",
      "description": "Build your business empire from a simple lemonade stand to a massive corporation! Hire managers, invest wisely, and become the ultimate capitalist.",
      "icon": "assets/adventure-capitalist.jpg",
      "link": null,
      "raw-game-link": "/game-assets/adventurecapitalist/index.html",
      "category": "Idle",
      "tags": ["business", "empire", "investment", "managers", "corporation", "capitalist", "incremental"]
    },
    {
      "id": 35,
      "gameId": "adventuredrivers",
      "name": "Adventure Drivers",
      "description": "Race through challenging terrain and perform stunts in this thrilling driving adventure! Navigate obstacles and reach the finish line in style.",
      "icon": "assets/adventure-drivers.png",
      "link": null,
      "raw-game-link": "/game-assets/adventuredrivers/index.html",
      "category": "Racing",
      "tags": ["driving", "adventure", "stunts", "terrain", "obstacles", "racing", "thrilling"]
    },
    {
      "id": 36,
      "gameId": "ageofwar",
      "name": "Age Of War",
      "description": "Defend your base and evolve through different ages in this strategic tower defense game! Build units, upgrade technology, and conquer your enemies.",
      "icon": "assets/age-of-war.jpg",
      "link": null,
      "raw-game-link": "/game-assets/ageofwar/index.html",
      "category": "Strategy",
      "tags": ["tower-defense", "strategy", "evolution", "ages", "units", "technology", "conquest"]
    },
    {
      "id": 37,
      "gameId": "ageofwar2",
      "name": "Age Of War 2",
      "description": "The epic sequel to Age of War! Command armies across multiple eras, from cavemen to futuristic soldiers in this enhanced strategy experience.",
      "icon": "assets/age-of-war-2.png",
      "link": null,
      "raw-game-link": "/game-assets/ageofwar2/index.html",
      "category": "Strategy",
      "tags": ["sequel", "strategy", "armies", "eras", "cavemen", "futuristic", "enhanced"]
    },
    {
      "id": 38,
      "gameId": "arcadecardrift",
      "name": "Arcade Car Drift",
      "description": "Master the art of drifting in this arcade-style racing game! Slide around corners, earn points, and unlock new cars in fast-paced drift challenges.",
      "icon": "assets/arcade-car-drift.png",
      "link": null,
      "raw-game-link": "/game-assets/arcade-car-drift/index.html",
      "category": "Racing",
      "tags": ["drifting", "arcade", "racing", "corners", "points", "cars", "fast-paced"]
    },
    {
      "id": 39,
      "gameId": "archeryworldtour",
      "name": "Archery World Tour",
      "description": "Travel the world and compete in archery tournaments! Aim carefully, account for wind, and hit bullseyes to become the world champion archer.",
      "icon": "assets/archery-world-tour.jpg",
      "link": null,
      "raw-game-link": "/game-assets/archery-world-tour/index.html",
      "category": "Sports",
      "tags": ["archery", "world", "tournaments", "aiming", "wind", "bullseye", "champion"]
    },
    {
      "id": 40,
      "gameId": "asmallworldcup",
      "name": "A Small World Cup",
      "description": "Compete in the ultimate soccer tournament! Control your team through matches and work your way up to win the World Cup in this exciting sports game.",
      "icon": "assets/a-small-world-cup.jpg",
      "link": null,
      "raw-game-link": "/game-assets/asmallworldcup/index.html",
      "category": "Sports",
      "tags": ["soccer", "world-cup", "tournament", "team", "matches", "sports", "competition"]
    },
    {
      "id": 41,
      "gameId": "awesometanks2",
      "name": "Awesome Tanks 2",
      "description": "Command powerful tanks in this action-packed sequel! Destroy enemies, upgrade your arsenal, and dominate the battlefield with strategic combat.",
      "icon": "assets/awesome-tanks-2.png",
      "link": null,
      "raw-game-link": "/game-assets/AwesomeTanks2/index.html",
      "category": "Action",
      "tags": ["tanks", "sequel", "combat", "upgrade", "battlefield", "strategy", "destruction"]
    },
    {
      "id": 42,
      "gameId": "backrooms",
      "name": "Backrooms",
      "description": "Navigate the endless yellow maze of the Backrooms in this eerie horror experience. Find your way out while avoiding the entities that lurk in the shadows.",
      "icon": "assets/backrooms.jpg",
      "link": null,
      "raw-game-link": "/game-assets/backrooms/index.html",
      "category": "Horror",
      "tags": ["horror", "maze", "backrooms", "entities", "eerie", "survival", "escape"]
    },
    {
      "id": 43,
      "gameId": "baconmaydie",
      "name": "Bacon May Die",
      "description": "Fight for survival as a piece of bacon in this intense action game! Battle through waves of enemies with various weapons and special abilities.",
      "icon": "assets/bacon-may-die.jpg",
      "link": null,
      "raw-game-link": "/game-assets/baconmaydie/index.html",
      "category": "Action",
      "tags": ["bacon", "survival", "fighting", "waves", "weapons", "abilities", "intense"]
    },
    {
      "id": 44,
      "gameId": "badicecream",
      "name": "Bad Ice Cream",
      "description": "Control ice cream characters in this fun puzzle game! Create and break ice blocks to collect fruit while avoiding enemies in maze-like levels.",
      "icon": "assets/bad-ice-cream.png",
      "link": null,
      "raw-game-link": "/game-assets/badicecream/index.html",
      "category": "Puzzle",
      "tags": ["ice-cream", "puzzle", "maze", "fruit", "blocks", "enemies", "multiplayer"]
    },
    {
      "id": 45,
      "gameId": "badicecream2",
      "name": "Bad Ice Cream 2",
      "description": "The sequel to Bad Ice Cream with new levels and challenges! Team up with friends to collect fruit and outsmart enemies in frozen mazes.",
      "icon": "assets/bad-ice-cream-2.png",
      "link": null,
      "raw-game-link": "/game-assets/badicecream2/index.html",
      "category": "Puzzle",
      "tags": ["sequel", "ice-cream", "puzzle", "multiplayer", "frozen", "teamwork", "challenges"]
    },
    {
      "id": 46,
      "gameId": "badicecream3",
      "name": "Bad Ice Cream 3",
      "description": "The third installment of the popular ice cream series! Explore new environments and face tougher challenges in this cooperative puzzle adventure.",
      "icon": "assets/bad-ice-cream-3.png",
      "link": null,
      "raw-game-link": "/game-assets/badicecream3/index.html",
      "category": "Puzzle",
      "tags": ["third", "installment", "ice-cream", "cooperative", "adventure", "environments", "challenges"]
    },
    {
      "id": 47,
      "gameId": "badtimesimulator",
      "name": "Bad Time Simulator",
      "description": "Experience the infamous Sans boss fight from Undertale! Test your reflexes and determination in this challenging bullet-hell battle simulator.",
      "icon": "assets/bad-time-simulator.png",
      "link": null,
      "raw-game-link": "/game-assets/badtimesimulator/index.html",
      "category": "Action",
      "tags": ["undertale", "sans", "boss-fight", "bullet-hell", "challenging", "reflexes", "simulator"]
    },
    {
      "id": 48,
      "gameId": "baldisbasics",
      "name": "Baldi's Basics",
      "description": "Collect all 7 notebooks and escape the school while avoiding Baldi and his friends in this horror-comedy educational parody game.",
      "icon": "assets/baldis-basics.png",
      "link": null,
      "raw-game-link": "/game-assets/baldis-basics/index.html",
      "category": "Horror",
      "tags": ["horror", "comedy", "educational", "parody", "school", "notebooks", "escape"]
    },
    {
      "id": 49,
      "gameId": "basketrandom",
      "name": "Basket Random",
      "description": "Play basketball with random physics and unpredictable gameplay! Score baskets in this hilarious and chaotic sports game with ever-changing rules.",
      "icon": "assets/basket-random.png",
      "link": null,
      "raw-game-link": "/game-assets/BasketRandom/index.html",
      "category": "Sports",
      "tags": ["basketball", "random", "physics", "chaotic", "hilarious", "unpredictable", "sports"]
    },
    {
      "id": 50,
      "gameId": "bigtowertinysquare",
      "name": "Big Tower Tiny Square",
      "description": "Navigate through a massive tower filled with deadly traps and precise platforming challenges. Help the tiny square rescue his pineapple!",
      "icon": "assets/big-tower-tiny-square.png",
      "link": null,
      "raw-game-link": "/game-assets/big-tower-tiny-square-2/index.html",
      "category": "Platformer",
      "tags": ["tower", "platformer", "precise", "traps", "challenging", "pineapple", "tiny"]
    },
    {
      "id": 51,
      "gameId": "bobtherobber2",
      "name": "Bob the Robber 2",
      "description": "Help Bob continue his thieving adventures in this stealth puzzle game! Sneak past guards, disable security systems, and steal valuable treasures.",
      "icon": "assets/bob-the-robber-2.png",
      "link": null,
      "raw-game-link": "/game-assets/bobtherobber2/index.html",
      "category": "Puzzle",
      "tags": ["stealth", "puzzle", "thief", "guards", "security", "treasures", "adventure"]
    },
    {
      "id": 52,
      "gameId": "boxingrandom",
      "name": "Boxing Random",
      "description": "Throw punches in this unpredictable boxing game with random physics! Fight your way to victory in hilarious and chaotic boxing matches.",
      "icon": "assets/boxing-random.png",
      "link": null,
      "raw-game-link": "/game-assets/Boxing-Random/index.html",
      "category": "Sports",
      "tags": ["boxing", "random", "physics", "fighting", "chaotic", "hilarious", "matches"]
    },
    {
      "id": 53,
      "gameId": "blumgiracers",
      "name": "Blumgi Racers",
      "description": "Race through colorful tracks with unique vehicles in this fun racing game! Master different driving mechanics and compete for the best times.",
      "icon": "assets/blumgi-racers.jpg",
      "link": null,
      "raw-game-link": "/game-assets/blumgiracers/index.html",
      "category": "Racing",
      "tags": ["racing", "colorful", "vehicles", "driving", "mechanics", "competition", "tracks"]
    },
    {
      "id": 54,
      "gameId": "bumbslime",
      "name": "Bumb Slime",
      "description": "Control a bouncy slime character through challenging platformer levels! Jump, bounce, and navigate obstacles in this adorable physics-based game.",
      "icon": "assets/bumb-slime.png",
      "link": null,
      "raw-game-link": "/game-assets/BlumgiSlime/index.html",
      "category": "Platformer",
      "tags": ["slime", "bouncy", "platformer", "physics", "adorable", "obstacles", "jumping"]
    }
  ]
};
